apiVersion: v1
kind: Service
metadata:
  name: redis-replica
  namespace: redis
  labels:         
    app: redis
    role: replica
spec:
  type: ClusterIP
  selector:
    app: redis
    role: replica
  ports:
    - name: redis
      port: 6382
      targetPort: 6382

