apiVersion: v1
kind: Service
metadata:
  name: redis-ops-api
  namespace: redis
spec:
  selector:
    app: redis-ops-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
