apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: redis
  labels:          
    app: redis
    role: master
spec:
  type: ClusterIP
  selector:
    app: redis     
    role: master
  ports:
    - name: redis
      port: 6381
      targetPort: 6381

